name: Publish NuGet Package

on:
  push:
    branches:
      - main
     paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'test/**'
      - '*.sln'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'

      - uses: dotnet/nbgv@master
        with:
          setAllVars: true

      - name: Build and pack
        run: dotnet restore
        run: dotnet build --configuration Release --no-restore
