name: Publish NuGet Package

on:
  # push:
  #   branches:
  #     - main
  #    paths-ignore:
  #     - 'README.md'
  #     - 'LICENSE'
  #     - 'test/**'
  #     - '*.sln'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      
      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: |
          current_date=$(echo "$(date +'%Y-%m-%d')")
          version_suffix="$current_date-${{ github.run_number }}"
          dotnet pack .\src\Yale\Yale.csproj --configuration Release --no-build --no-restore --include-symbols --include-source --version-suffix $version_suffix

      - name: Push
        run: dotnet nuget push ./src/**/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
